networks:
  default: 
    driver: bridge 
    name: roboshop
    #external: true  # I created network already using docker network create roboshop 
services: 
  mongodb:
   image: jyothinaga/mongodb:v1 
   container_name: mongodb 
  catalogue: 
    image: jyothinaga/catalogue:v1 
    container_name: catalogue 
    depends_on:
      - mongodb
  redis:
   image: redis:7.0
   container_name: redis 
  user: 
   image: jyothinaga/user:v1 
   container_name: user
   depends_on:
    - redis
    - mongodb     
  cart:
    image: jyothinag/cart:v1 
    container_name: cart 
    depends_on :
     -catalogue
     -redis 
  mysql: 
   image: jyothinaga/mysql:v1 
   container_name: mysql 
  shipping: 
    image: jyothinaga/shipping:v1 
    container_name: shipping 
    depends_on :
      -mysql 
      -cart      